version: "3.1"
services:
  scheduler:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw

  webserver:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
    ports:
      - "8081:8080"  

  triggerer:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
